version: "3"

services:
  chirpstack-network-server:
    image: chirpstack/chirpstack-network-server:3
    environment:
      - POSTGRESQL__DSN=postgres://chirpstack_ns:chirpstack_ns@postgresql/chirpstack_ns?sslmode=disable
      - REDIS__URL=redis://redis:6379
      - NETWORK_SERVER__BAND__NAME=EU868
      - NETWORK_SERVER__GATEWAY__BACKEND__MQTT__USERNAME=$MQTT_USERNAME
      - NETWORK_SERVER__GATEWAY__BACKEND__MQTT__PASSWORD=$MQTT_PASSWORD
      - NETWORK_SERVER__GATEWAY__BACKEND__MQTT__SERVER=tcp://$MOSQUITTO_IP:$MOSQUITTO_PORT
      - JOIN_SERVER__DEFAULT__SERVER=http://chirpstack-application-server:8003
    depends_on:
      - postgresql

  chirpstack-network-server-us:
    image: chirpstack/chirpstack-network-server:3
    environment:
      - POSTGRESQL__DSN=postgres://chirpstack_ns_us:chirpstack_ns_us@postgresql/chirpstack_ns_us?sslmode=disable
      - REDIS__URL=redis://redis:6379
      - NETWORK_SERVER__BAND__NAME=US915
      - NETWORK_SERVER__GATEWAY__BACKEND__MQTT__SERVER=tcp://$MOSQUITTO_IP:$MOSQUITTO_PORT
      - NETWORK_SERVER__GATEWAY__BACKEND__MQTT__USERNAME=$MQTT_USERNAME
      - NETWORK_SERVER__GATEWAY__BACKEND__MQTT__PASSWORD=$MQTT_PASSWORD
      - JOIN_SERVER__DEFAULT__SERVER=http://chirpstack-application-server:8003
      - APPL
    depends_on:
      - postgresql

  chirpstack-application-server:
    image: chirpstack/chirpstack-application-server:3
    ports:
      - 8080:8080
    environment:
      - POSTGRESQL__DSN=postgres://chirpstack_as:chirpstack_as@postgresql/chirpstack_as?sslmode=disable
      - REDIS__URL=redis://redis:6379
      - APPLICATION_SERVER__INTEGRATION__MQTT__SERVER=tcp://$MOSQUITTO_IP:$MOSQUITTO_PORT
      - APPLICATION_SERVER__INTEGRATION__MQTT__USERNAME=$MQTT_USERNAME
      - APPLICATION_SERVER__INTEGRATION__MQTT__PASSWORD=$MQTT_PASSWORD
      - APPLICATION_SERVER__API__PUBLIC_HOST=chirpstack-application-server:8001
      - APPLICATION_SERVER__EXTERNAL_API__JWT_SECRET=verysecret
    depends_on:
      - chirpstack-network-server
      - chirpstack-network-server-us

  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:3
    ports:
      - 1700:1700/udp
    environment:
      - INTEGRATION__MQTT__AUTH__GENERIC__SERVERS=tcp://$MOSQUITTO_IP:$MOSQUITTO_PORT
      - INTEGRATION__MQTT__AUTH__GENERIC__USERNAME=$MQTT_USERNAME
      - INTEGRATION__MQTT__AUTH__GENERIC__PASSWORD=$MQTT_PASSWORD

  postgresql:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=root 
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    volumes:
      - redisdata:/data


volumes:
  postgresqldata:
  redisdata:
